### ISSUE TITLE
Question about Model & add/get States

### ISSUE THREAD

**Issue by Pi3rr3DS** [lexik/LexikWorkflowBundle#26]
I have made a model for my entity which implements ModelInterface and ModelStateInterface

My model : 
```
<?php
namespace myProject\myBundle\WorkFlow\Model;

use Lexik\Bundle\WorkflowBundle\Model\ModelInterface;
use Lexik\Bundle\WorkflowBundle\Model\ModelStateInterface;
use Lexik\Bundle\WorkflowBundle\Entity\ModelState;
use myProject\myBundle\Entity\myEntity;

class myModel implements ModelInterface, ModelStateInterface
{ 
    ... 
    public function addState(ModelState $modelState)
    {
        $this->myEntity->setStates[] = $modelState;
    }

    public function getStates()
    {
        return $this->myEntity->getStates;
    }
}
```

Entity side added parameter (getter and setters by doctrine) :
```
    /**
     * @ORM\Column(nullable=true, name="States", type="array")
     */
    protected $states = array(); 

    /**
     * @ORM\Column(nullable=true, name="Status", type="smallint")
     */
    private $Status;
```

In my controller i do : 
```
$em = $this->getDoctrine()->getManager();
$em->getConnection()->beginTransaction();
try {
    // persist 1st my entity to get the entity id
    $em->persist($myEntity);
    $em->flush();

    // next create modelstate and update status in my entity
    $myEntityModel = new MyModel($myEntity);
    $processHandler = $this->get('lexik_workflow.handler.myprocess');
    $ModelState = $processHandler->start($myEntityModel)
    $em->flush();
    $em->getConnection()->commit();

} catch (WorkflowException $e) {
    $em->getConnection()->rollback();
    $em->close();
}
```

1) I have to implement addStates and getStates into the model or directly into the entity ?

2) Is it the best way in my controller to try / catch and reverse if WorkFlowException ?

3) My entity is ALWAYS saved in DB with States => empty array, why ?
```
    // This code doesn't work :(
    $myEntityModel->addState($ModelState)
```
4) Why there is an objects option into getStates, we have to do it from the entity model, no ?

Sorry for my bad english !

**Comment by cedric-g** [comment]
Hi, you have to implement `ModelStateInterface` on the same class that implements `ModelInterface`. If you want to get states for a given model don't forget to call 
`$container->get('lexik_workflow.model_storage')->setStates($model);` this will fill the object with its states, then you can call `$model->getStates()`. This is used to read states from th DB and display them, you don't need to map the` $states` property on your Doctrine model.

**Comment by Pi3rr3DS** [comment]
Thanks for you'r answer, solved my problem +1:
