### ISSUE TITLE
Progress History Log in this workflow bundle

### ISSUE THREAD

**Issue by Mentos93** [lexik/LexikWorkflowBundle#27]
Is it possible that this bundle can keep track of the progress of a work flow?

What I mean; is it possible to save each action in a database table? Like John Doe created the first draft on yyyy/mm/dd. When someone approve it, another row gets added; Admin Jack approved draft on yyyy/mm/dd...

I am going to implement this work flow bundle, and I need to log all user actions as well, so I wonder if it can be accomplished with this or should I look for another bundle or develop that myself?

Thank you

**Comment by alafon** [comment]
This is already the case. There is an entity here : https://github.com/lexik/LexikWorkflowBundle/blob/master/Entity/ModelState.php

It save the each state with custom information in the `data` property. These data are retrieved from the getWorkflowData() method of model object. You need to implement this model as described here : https://github.com/lexik/LexikWorkflowBundle#model-object

Last but not least, if you need more (custom actions depending on the step you reached for instance), you can implement Event Subscribers as described here (for the xxxx.xxxx.reached event) : https://github.com/lexik/LexikWorkflowBundle#step-actions

**Comment by Siempie93** [comment]
Thank you very much alafon! I see now.

**Comment by alafon** [comment]
You're welcome @Mentos93
